### ISSUE TITLE
you stole my code

### ISSUE THREAD

**Issue by DingoHackz** [LucasBreeden/InsaneObjectsDownloader#1]
you're straight out of your damn mind

do you have any idea who I am? do you know how dangerous I am? I own the Ratting Mafia. I am DingoHackz. I got hella booters. Booters. I got booters connected to my botnet. I have 33 TBPS of data I can send to your entire country this second, faggot. You better stop stealing my code. 

- Lucas K. Breeden

This is your last and only warning.

**Comment by LucasBreeden** [comment]
no❤️️

**Comment by DingoHackz** [comment]
follow my deviantart https://www.deviantart.com/dingohackz/
